#
# Makefile for the i2c core.
#


obj-$(CONFIG_MC_GPIO_SUPPORT)			+= mc_gpio/
obj-$(CONFIG_MC_I2C_SUPPORT)			+= mc_i2c/
obj-$(CONFIG_MC_SPI_SUPPORT)			+= mc_spi/
obj-$(CONFIG_MC_PWM_SUPPORT)			+= mc_pwm/


